name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: job1-step
      run: echo hello world

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - name: job2-step
      run: echo hello world

  job3:
    runs-on: ubuntu-latest
    steps:
    - name: job3-step
      run: |
        echo hello world
        exit 1

  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
    - name: job4-step
      run: echo hello world
