name: path-filter
on:
  push:
    paths:
    - '.github/workflows/part2/*'
    - '!.github/workflows/part1/push.yaml'

jobs:
  path-fitler:
    runs-on: ubuntu-latest
    steps:
    - name: echo hello
      run: echo hello