name: output
on: push

jobs:
  create-output:
    runs-on: ubuntu-latest
    steps:
    - name: echo output
      id: output-id1
      run: |
        echo "test=hello" >> $GITHUB_OUTPUT
    - name: check output
      run: |
        echo ${{ steps.output-id1.outputs.test }}