name: "PR 브랜치 검증 및 생성자 출력"

on:
  pull_request:
    types: [opened]    # PR 오픈 시에만 실행

jobs:
  branch_check:
    name: "베이스 브랜치가 dev인지 확인"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "베이스 브랜치 검사"
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          if [ "$BASE_BRANCH" != "dev" ]; then
            echo "::error ::PR 베이스 브랜치가 dev가 아닙니다 (현재: $BASE_BRANCH)"
            exit 1
          fi

  print_creator:
    name: "PR 생성자 이름 출력"
    runs-on: ubuntu-latest
    needs: branch_check    # branch_check 가 성공해야 실행
    steps:
      - name: "생성자 로그인 아이디 출력"
        run: |
          CREATOR="${{ github.event.pull_request.user.login }}"
          echo "PR 생성자: $CREATOR"
