name: "외부 환경 변수 시크릿으로 가져오기"

on:
  pull_request:
    types: [opened]    # PR 오픈 시에만 실행

jobs:
  test_scret_env:
    name: "외부 시크릿 env 테스트"
    runs-on: ubuntu-latest
    steps:

      - name: "secret env"
        run: |
          echo ${{ secrets.test }}
